// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/akaimo/job-observer/pkg/apis/jobobserver/v1alpha1"
	scheme "github.com/akaimo/job-observer/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// NotificatorsGetter has a method to return a NotificatorInterface.
// A group's client should implement this interface.
type NotificatorsGetter interface {
	Notificators(namespace string) NotificatorInterface
}

// NotificatorInterface has methods to work with Notificator resources.
type NotificatorInterface interface {
	Create(*v1alpha1.Notificator) (*v1alpha1.Notificator, error)
	Update(*v1alpha1.Notificator) (*v1alpha1.Notificator, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Notificator, error)
	List(opts v1.ListOptions) (*v1alpha1.NotificatorList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Notificator, err error)
	NotificatorExpansion
}

// notificators implements NotificatorInterface
type notificators struct {
	client rest.Interface
	ns     string
}

// newNotificators returns a Notificators
func newNotificators(c *JobObserverV1alpha1Client, namespace string) *notificators {
	return &notificators{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the notificator, and returns the corresponding notificator object, and an error if there is any.
func (c *notificators) Get(name string, options v1.GetOptions) (result *v1alpha1.Notificator, err error) {
	result = &v1alpha1.Notificator{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("notificators").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Notificators that match those selectors.
func (c *notificators) List(opts v1.ListOptions) (result *v1alpha1.NotificatorList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.NotificatorList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("notificators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested notificators.
func (c *notificators) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("notificators").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a notificator and creates it.  Returns the server's representation of the notificator, and an error, if there is any.
func (c *notificators) Create(notificator *v1alpha1.Notificator) (result *v1alpha1.Notificator, err error) {
	result = &v1alpha1.Notificator{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("notificators").
		Body(notificator).
		Do().
		Into(result)
	return
}

// Update takes the representation of a notificator and updates it. Returns the server's representation of the notificator, and an error, if there is any.
func (c *notificators) Update(notificator *v1alpha1.Notificator) (result *v1alpha1.Notificator, err error) {
	result = &v1alpha1.Notificator{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("notificators").
		Name(notificator.Name).
		Body(notificator).
		Do().
		Into(result)
	return
}

// Delete takes name of the notificator and deletes it. Returns an error if one occurs.
func (c *notificators) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("notificators").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *notificators) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("notificators").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched notificator.
func (c *notificators) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Notificator, err error) {
	result = &v1alpha1.Notificator{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("notificators").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
