---
# Source: job-observer/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: "job-observer"
  labels:
    helm.sh/chart: job-observer-0.1.5
---
# Source: job-observer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-observer
  namespace: "job-observer"
  labels:
    app: job-observer
    helm.sh/chart: job-observer-0.1.5
---
# Source: job-observer/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cleaners.job-observer.akaimo.com
spec:
  group: job-observer.akaimo.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ttlAfterFinished:
                  type: string
                cleaningJobStatus:
                  type: string
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
              required:
                - ttlAfterFinished
                - selector
      additionalPrinterColumns:
        - name: message
          type: string
          description: message content which want to show
          jsonPath: .status.message
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: cleaners
    singular: cleaner
    kind: Cleaner
---
# Source: job-observer/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: job-observer
  labels:
    app: job-observer
    helm.sh/chart: job-observer-0.1.5
rules:
  - apiGroups: ["job-observer.akaimo.com"]
    resources: ["cleaners"]
    verbs: ["list", "watch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["list", "watch", "delete"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
# Source: job-observer/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: job-observer
  labels:
    app: job-observer
    helm.sh/chart: job-observer-0.1.5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-observer
subjects:
  - kind: ServiceAccount
    name: job-observer
    namespace: "job-observer"
---
# Source: job-observer/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-observer:leaderelection
  namespace: "job-observer"
  labels:
    app: job-observer
    helm.sh/chart: job-observer-0.1.5
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    resourceNames: ["job-observer-controller"]
    verbs: ["get", "update", "patch"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["create"]
---
# Source: job-observer/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-observer:leaderelection
  namespace: "job-observer"
  labels:
    app: job-observer
    helm.sh/chart: job-observer-0.1.5
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-observer:leaderelection
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: job-observer
    namespace: "job-observer"
---
# Source: job-observer/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-observer
  namespace: "job-observer"
  labels:
    app: job-observer
    helm.sh/chart: job-observer-0.1.5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-observer
  template:
    metadata:
      labels:
        app: job-observer
        helm.sh/chart: job-observer-0.1.5
    spec:
      serviceAccount: job-observer
      containers:
        - name: job-observer
          image: "ghcr.io/akaimo/job-observer:0.1.3"
          imagePullPolicy: IfNotPresent
          args:
            - /job-observer
            - --leader-election-namespace=job-observer
          resources:
            {}
