---
# Source: job-observer/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name: "job-observer"
  labels:
    helm.sh/chart: job-observer-0.1.1
---
# Source: job-observer/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-observer
  namespace: "job-observer"
  labels:
    app: job-observer
    helm.sh/chart: job-observer-0.1.1
---
# Source: job-observer/templates/crds.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cleaners.job-observer.akaimo.com
spec:
  group: job-observer.akaimo.com
  version: v1alpha1
  scope: Namespaced
  names:
    plural: cleaners
    singular: cleaner
    kind: Cleaner
  subresources:
    status: {}
  additionalPrinterColumns:
    - name: message
      type: string
      description: message content which want to show
      JSONPath: .status.message
    - name: AGE
      type: date
      JSONPath: .metadata.creationTimestamp
  validation:
    openAPIV3Schema:
      type: object
      properties:
        spec:
          properties:
            ttlAfterFinished:
              type: string
            cleaningJobStatus:
              type: string
            selector:
              type: object
              properties:
                matchLabels:
                  type: object
          required:
            - ttlAfterFinished
            - selector
---
# Source: job-observer/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: job-observer
  labels:
    app: job-observer
    helm.sh/chart: job-observer-0.1.1
rules:
  - apiGroups:
      - "job-observer.akaimo.com"
      - "batch"
    resources:
      - "cleaners"
      - "jobs"
    verbs:
      - "list"
      - "watch"
      - "delete"
---
# Source: job-observer/templates/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: job-observer
  labels:
    app: job-observer
    helm.sh/chart: job-observer-0.1.1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-observer
subjects:
  - kind: ServiceAccount
    name: job-observer
    namespace: "job-observer"
---
# Source: job-observer/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-observer
  namespace: "job-observer"
  labels:
    app: job-observer
    helm.sh/chart: job-observer-0.1.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: job-observer
      helm.sh/chart: job-observer-0.1.1
  template:
    metadata:
      labels:
        app: job-observer
        helm.sh/chart: job-observer-0.1.1
    spec:
      serviceAccount: job-observer
      containers:
        - name: job-observer
          image: "ghcr.io/akaimo/job-observer:0.1.1"
          imagePullPolicy: IfNotPresent
          resources:
            {}
