apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cleaners.job-observer.akaimo.com
spec:
  group: job-observer.akaimo.com
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                ttlAfterFinished:
                  type: string
                cleaningJobStatus:
                  type: string
                selector:
                  type: object
                  properties:
                    matchLabels:
                      type: object
              required:
                - ttlAfterFinished
                - selector
      additionalPrinterColumns:
        - name: message
          type: string
          description: message content which want to show
          jsonPath: .status.message
        - name: AGE
          type: date
          jsonPath: .metadata.creationTimestamp
      subresources:
        status: {}
  scope: Namespaced
  names:
    plural: cleaners
    singular: cleaner
    kind: Cleaner
