apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-observer
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: job-observer
    helm.sh/chart: {{ template "job-observer.chart" . }}
spec:
  replicas: {{ .Values.controller.replicas }}
  selector:
    matchLabels:
      app: job-observer
  template:
    metadata:
      labels:
        app: job-observer
        helm.sh/chart: {{ template "job-observer.chart" . }}
    spec:
      serviceAccount: job-observer
      containers:
        - name: job-observer
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - /job-observer
            - --leader-election-namespace={{ .Release.Namespace }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
