// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/akaimo/job-observer/pkg/apis/cleaner/v1alpha1"
	"github.com/akaimo/job-observer/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type CleanerV1alpha1Interface interface {
	RESTClient() rest.Interface
	CleanersGetter
}

// CleanerV1alpha1Client is used to interact with features provided by the cleaner.akaimo.com group.
type CleanerV1alpha1Client struct {
	restClient rest.Interface
}

func (c *CleanerV1alpha1Client) Cleaners(namespace string) CleanerInterface {
	return newCleaners(c, namespace)
}

// NewForConfig creates a new CleanerV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*CleanerV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &CleanerV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new CleanerV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CleanerV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new CleanerV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *CleanerV1alpha1Client {
	return &CleanerV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CleanerV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
