// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	cleanerv1alpha1 "github.com/akaimo/job-observer/pkg/apis/cleaner/v1alpha1"
	versioned "github.com/akaimo/job-observer/pkg/client/clientset/versioned"
	internalinterfaces "github.com/akaimo/job-observer/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/akaimo/job-observer/pkg/client/listers/cleaner/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// NotificatorInformer provides access to a shared informer and lister for
// Notificators.
type NotificatorInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.NotificatorLister
}

type notificatorInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewNotificatorInformer constructs a new informer for Notificator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewNotificatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredNotificatorInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredNotificatorInformer constructs a new informer for Notificator type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredNotificatorInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JobObserverV1alpha1().Notificators(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.JobObserverV1alpha1().Notificators(namespace).Watch(options)
			},
		},
		&cleanerv1alpha1.Notificator{},
		resyncPeriod,
		indexers,
	)
}

func (f *notificatorInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredNotificatorInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *notificatorInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cleanerv1alpha1.Notificator{}, f.defaultInformer)
}

func (f *notificatorInformer) Lister() v1alpha1.NotificatorLister {
	return v1alpha1.NewNotificatorLister(f.Informer().GetIndexer())
}
