// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// NotificatorListerExpansion allows custom methods to be added to
// NotificatorLister.
type NotificatorListerExpansion interface{}

// NotificatorNamespaceListerExpansion allows custom methods to be added to
// NotificatorNamespaceLister.
type NotificatorNamespaceListerExpansion interface{}
