// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// CleanerListerExpansion allows custom methods to be added to
// CleanerLister.
type CleanerListerExpansion interface{}

// CleanerNamespaceListerExpansion allows custom methods to be added to
// CleanerNamespaceLister.
type CleanerNamespaceListerExpansion interface{}
