// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/akaimo/job-observer/pkg/apis/jobobserver/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNotificators implements NotificatorInterface
type FakeNotificators struct {
	Fake *FakeJobObserverV1alpha1
	ns   string
}

var notificatorsResource = schema.GroupVersionResource{Group: "job-observer.akaimo.com", Version: "v1alpha1", Resource: "notificators"}

var notificatorsKind = schema.GroupVersionKind{Group: "job-observer.akaimo.com", Version: "v1alpha1", Kind: "Notificator"}

// Get takes name of the notificator, and returns the corresponding notificator object, and an error if there is any.
func (c *FakeNotificators) Get(name string, options v1.GetOptions) (result *v1alpha1.Notificator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(notificatorsResource, c.ns, name), &v1alpha1.Notificator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Notificator), err
}

// List takes label and field selectors, and returns the list of Notificators that match those selectors.
func (c *FakeNotificators) List(opts v1.ListOptions) (result *v1alpha1.NotificatorList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(notificatorsResource, notificatorsKind, c.ns, opts), &v1alpha1.NotificatorList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NotificatorList{ListMeta: obj.(*v1alpha1.NotificatorList).ListMeta}
	for _, item := range obj.(*v1alpha1.NotificatorList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested notificators.
func (c *FakeNotificators) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(notificatorsResource, c.ns, opts))

}

// Create takes the representation of a notificator and creates it.  Returns the server's representation of the notificator, and an error, if there is any.
func (c *FakeNotificators) Create(notificator *v1alpha1.Notificator) (result *v1alpha1.Notificator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(notificatorsResource, c.ns, notificator), &v1alpha1.Notificator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Notificator), err
}

// Update takes the representation of a notificator and updates it. Returns the server's representation of the notificator, and an error, if there is any.
func (c *FakeNotificators) Update(notificator *v1alpha1.Notificator) (result *v1alpha1.Notificator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(notificatorsResource, c.ns, notificator), &v1alpha1.Notificator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Notificator), err
}

// Delete takes name of the notificator and deletes it. Returns an error if one occurs.
func (c *FakeNotificators) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(notificatorsResource, c.ns, name), &v1alpha1.Notificator{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNotificators) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(notificatorsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NotificatorList{})
	return err
}

// Patch applies the patch and returns the patched notificator.
func (c *FakeNotificators) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Notificator, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(notificatorsResource, c.ns, name, pt, data, subresources...), &v1alpha1.Notificator{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.Notificator), err
}
