// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/akaimo/job-observer/pkg/client/clientset/versioned/typed/notificator/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeJobObserverV1alpha1 struct {
	*testing.Fake
}

func (c *FakeJobObserverV1alpha1) Notificators(namespace string) v1alpha1.NotificatorInterface {
	return &FakeNotificators{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeJobObserverV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
