apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-observer
  namespace: job-observer
  labels:
    app: job-observer
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: job-observer
  labels:
    app: job-observer
rules:
  - apiGroups:
      - "job-observer.akaimo.com"
      - "batch"
    resources:
      - "cleaner"
      - "jobs"
    verbs:
      - "list"
      - "watch"
      - "delete"
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: job-observer
  labels:
    app: job-observer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: job-observer
subjects:
  - kind: ServiceAccount
    name: job-observer
    namespace: default
